# -*- coding: utf-8 -*-
"""Digit Recognizer - MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DgNbIUuZ4_4W18IfZRi7cmIHFZT0gKLP
"""

import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout

from sklearn.metrics import confusion_matrix

test_df = pd.read_csv('test.csv')

train_df = pd.read_csv('train.csv')

train_df.shape

test_df.shape